### ISSUE TITLE
eLife paper archive dead

### ISSUE THREAD

**Issue by bencevans** [sciencefair-land/sciencefair#172]
The metadata for eLife has a few peers available however the content archive appears to be dead. Does anyone have a copy of `dat://07e82e6ea1ab7e7c3d4872f035b2320e8aefe26ba35033b983f4b2e033d07d44` we can put up to seed a bit?

**Comment by bencevans** [comment]
```
$ dat clone dat://07e82e6ea1ab7e7c3d4872f035b2320e8aefe26ba35033b983f4b2e033d07d44 eLife
dat v13.11.4
Cloning: 52337 files (6.3 GB)

3 connections | Download 0 B/s Upload 0 B/s

Downloading updates...
[==----------------------------------------] 6.14%


```

looks like someone came online in the last 24h. whoever it may be please come back! :pray:

**Comment by joehand** [comment]
The place the old content was hosted got accidentally wiped by the hosting company...

Rik will try to get another copy back up soon. I do have it on the server, so you should be able to get that content (34% downloaded there). But not sure why you're not connecting there...

**Comment by blahah** [comment]
@bencevans I have the original data and also have some code locally for regenerating the data source with the latest papers. It's ironic that this whole system should be more reliable than the normal web once it's properly set up, but it is currently in a state that doesn't reach that potential (largely because I had to stop working on everything due to illness).

It's encouraging to see continued interest in ScienceFair so I will start working my way through the issues to get everything moving again. Thanks for taking the time to check out the project and make thoughtful issue reports @bencevans :)

**Comment by bencevans** [comment]
@joehand interesting. I had problems connecting when trying to transfer a dataset using Dat with someone the other day. My side definitely and most likely the other person on a home/consumer internet connection/routers. However using WebTorrent worked find. Led me to wonder if WebTorrent can do the NAT hole-punching but not Dat. Maybe WebTorrent uses TURN relays. Only ideas at the moment, would need a lot more time to investigate.

@blahah that's great news! If there's something I can help with I'm in the IRC channel. This seemed like a really interesting project to get stuck in with learning the ins and outs of the Dat ecosystem. I'm particularly interested in getting the arXiv available too (CS/ML background here). Hope you've regained your health bar! :sparkles:
